#!/bin/bash
#creating mount point
mkdir /media/ETS

#creating config dir
mkdir /etc/ETSTools

#creating default credential (empty)
while true; do
	echo "Enter ETS username followed by ENTER"
	read USER
	len="${#USER}"
	if [ $len -lt 7 ]; then
		echo "Username seem invalid"
	else
		break
	fi
done
while true; do
	echo "Enter ETS password followed by ENTER"
	read PWD
	len="${#PWD}"
	if [ $len -lt 8 ]; then
		echo "Password seem invalid"
	else
		break
	fi
done
echo "username=$USER
password=$PWD" > /etc/ETSTools/credential


#setup script into dispacher
cp 99-EtsSmb /etc/NetworkManager/dispatcher.d/
